# bundle workflow

name: bundle-runner-workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches: [ master ]
    paths:
    - 'terraform/dev/**_bundle.tf'

  workflow_call:
    inputs:
      pick_deploy_environment:
        required: true
        type: string
    outputs:
      bundle_runner_result:
        description: "bundle runner result"
        value: ${{ jobs.display_inputs.outputs.bundle_runner_result }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  display_inputs:
    runs-on: [ubuntu-latest]
    outputs:
      bundle_runner_result: ${{ steps.return_results.outputs.bundle_runner_result }}

    steps:
    - id: checkout_repo
      uses: actions/checkout@v2
      with:
        clean: 'true'
        persist-credentials: 'false'

    - id: display_inputs
      run: |
        echo ${{inputs.pick_deploy_environment}}

    - id: return_results
      run: |
        echo "::set-output name=bundle_runner_result::passing"
        echo git diff-tree --no-commit-id --name-status -r ${{ github.sha }}
        echo $(git diff-tree --no-commit-id --name-status -r ${{ github.sha }})
        echo "$(git diff-tree --no-commit-id --name-status -r ${{ github.sha }})"



