on: 
  workflow_dispatch:
    inputs:
      deploy_account:
        description: 'AWS S3 to push lambda to, dev or prod.'
        required: true
        type: choice
        options:
        - dev
        - prod
        - ubuntu-latest

name: metrics_lambda_builder

jobs:
  set_deploy_env:
    runs-on: [ ubuntu-latest ]
    outputs:
      runner: ${{ steps.set_deploy_env.outputs.runner }}

    steps:
    - id: set_deploy_env
      run: |

        if [[ "${{ github.event.inputs.deploy_account }}" == prod ]]; then
          echo "::set-output name=runner::prod"
        else
          echo "::set-output name=runner::dev"
        fi
        echo "Selected runner:${{steps.set_deploy_env.outputs.runner}}"

  clean_workspace:
    needs: set_deploy_env
    runs-on: ${{needs.set_deploy_env.outputs.runner}}

    steps:

    - name: display
      run: |
        ls -la
