on:
  workflow_dispatch:
    inputs:
      deploy_account:
        description: 'AWS S3 to push lambda to, dev or prod.'
        required: true
        type: choice
        options:
        - dev
        - prod
        - ubuntu-latest

name: metrics_lambda_builder

jobs:
  set_deploy_env:
    runs-on: [dev]
    outputs:
      runner: ${{ steps.set_deploy_env.outputs.runner }}

    steps:
    - id: set_deploy_env
      run: |
        echo "::set-output name=runner::${{ github.event.inputs.deploy_account }}"

  clean_workspace:
    needs: set_deploy_env
    runs-on: ${{needs.set_deploy_env.outputs.runner}}

    steps:
    - name: Clean workspace
      run: |
        echo "Cleaning up run"
        rm -rf "${{ github.workspace }}"

  deploy:
    name: Deploy
    needs: [set_deploy_env, clean_workspace]
    runs-on: ${{needs.set_deploy_env.outputs.runner}}

    steps:
    - name: display
      run: |
        ls -la
