on: 
  repository_dispatch:
    types: [build_metrics_lambda]

name: metrics_lambda 

jobs:
  clean_workspace:
    runs-on: [ubuntu-latest]

    steps:
    - name: Clean workspace
      run: |
        echo "Cleaning up run"

